[package]
name = "web-controller"
version = "0.1.0"
edition = "2024"

[dependencies]
ascot.version = "0.1.0"
ascot.git = "https://github.com/SoftengPoliTo/ascot"
ascot.branch = "controller"

ascot-controller.version = "0.1.0"
ascot-controller.git = "https://github.com/SoftengPoliTo/ascot"
ascot-controller.branch = "controller"

axum.version = "0.8.0"
axum.default-features = false
axum.features = ["tokio", "http1", "http2", "form", "json"]

chrono.version = "0.4"
chrono.default-features = false
chrono.features = ["clock"]

clap.version = "4.5"
clap.default-features = false
clap.features = ["derive", "std"]

minijinja.version = "2.10.0"

serde.version = "1.0"
serde.default-features = false
serde.features = ["derive"]

serde_json.version = "1"
serde_json.default-features = false
serde_json.features = ["alloc"]

tokio.version = "1.0"
tokio.default-features = false
tokio.features = ["rt-multi-thread"]

tower-http.version = "0.6.1"
tower-http.default-features = false
tower-http.features = ["fs", "trace"]

tracing.version = "0.1"
tracing.default-features = false
tracing.optional = true

tracing-subscriber.version = "0.3"
tracing-subscriber.default-features = false
tracing-subscriber.features = ["fmt", "json", "ansi"]
tracing-subscriber.optional = true

# TODO: Remove fake devices feature from default
[features]
default = ["logging", "fake-devices"]
logging = ["tracing", "tracing-subscriber"]
italian = []
fake-devices = []

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = "unwind"
incremental = false
overflow-checks = false
strip = "debuginfo"
